/* Auth */
export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const GET_DEVICE_TOKEN = 'GET_DEVICE_TOKEN'
export const LOGOUT = 'LOGOUT'

/* Tag Managing */
export const CREATE_TAG = 'CREATE_TAG'
export const DELETE_TAG = 'DELETE_TAG'
export const REQUEST_TAG = 'REQUEST_TAG'
export const ERROR_REQUEST_TAG = 'ERROR_REQUEST_TAG'
export const GET_LIST_TAGS = 'GET_LIST_TAGS'
export const ORDER_TAG = 'ORDER_TAG'

/* Notice */
export const REQUEST_NOTICE = 'REQUEST_NOTICE'
export const GET_LIST_NOTICES = 'GET_LIST_NOTICES'
export const ERROR_REQUEST_NOTICE = 'ERROR_REQUEST_NOTICE'
export const NOTICE_DELETE = 'NOTICE_DELETE'
export const EDIT_NOTICE = 'EDIT_NOTICE'
export const ADD_NOTICE = 'ADD_NOTICE'

/* Best Decorating */
export const REQUEST_BESTDECORATING = 'REQUEST_BESTDECORATING'
export const GET_LIST_BESTDECORATING = 'GET_LIST_BESTDECORATING'
export const BEST_DECORATING_ERROR_REQUEST = 'BEST_DECORATING_ERROR_REQUEST'
export const UPDATE_ORDER_BESTDECORATING = 'UPDATE_ORDER_BESTDECORATING'

/* Post Managing */
export const REQUEST_POST_MANAGING = 'REQUEST_POST_MANAGING'
export const GET_LIST_POST_MANAGING = 'GET_LIST_POST_MANAGING'
export const POST_MANAGING_DETAIL = 'POST_MANAGING_DETAIL'
export const POST_DETAIL_DELETE = 'POST_DETAIL_DELETE'
export const SET_PAGINATION = 'SET_PAGINATION'
export const SET_FORMDATA_GLOBAL = 'SET_FORMDATA_GLOBAL'
export const TOGGLE_RECOMMEND_POST = 'TOGGLE_RECOMMEND_POST'
export const GET_LIST_COMMENT_IN_POSTS = 'GET_LIST_COMMENT_IN_POSTS'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const DELETE_REPLY_IN_COMMENT = 'DELETE_REPLY_IN_COMMENT'
export const POST_MANAGING_REQUEST_ERROR = 'POST_MANAGING_REQUEST_ERROR'

/* User Managing */
export const REQUEST_USER_MANAGING = 'REQUEST_USER_MANAGING'
export const GET_LIST_USERS = 'GET_LIST_USERS'
export const SET_PAGINATION_USERMANAGING = 'SET_PAGINATION_USERMANAGING'
export const GET_USER_DETAIL = 'GET_USER_DETAIL'
export const TOGGLE_RECOMMEND_USER = 'TOGGLE_RECOMMEND_USER'
export const GET_LIST_REPORTED_IN_USER_DETAIL =
  'GET_LIST_REPORTED_IN_USER_DETAIL'
export const REQUEST_USER_MANAGING_ERROR = 'REQUEST_USER_MANAGING_ERROR'

/* Best User */
export const GET_LIST_BEST_USER = 'GET_LIST_BEST_USER'
export const UPDATE_ORDER_BEST_USER = 'UPDATE_ORDER_BEST_USER'
export const BEST_USER_REQUEST_ERROR = 'BEST_USER_REQUEST_ERROR'

/* Report Block Managing */
export const GET_LIST_REPORT_BLOCK_MANAGING = 'GET_LIST_REPORT_BLOCK_MANAGING'
export const GET_REPORT_BLOCK_DETAIL = 'GET_REPORT_BLOCK_DETAIL'
export const GET_HISTORY_REPORTED_IN_REPORT_BLOCK_DETAIL =
  'GET_HISTORY_REPORTED_IN_REPORT_BLOCK_DETAIL'
export const GET_HISTORY_REPORTED_DETAIL = 'GET_HISTORY_REPORTED_DETAIL'
export const REPORT_BLOCK_MANAGING_REQUEST_ERROR =
  'REPORT_BLOCK_MANAGING_REQUEST_ERROR'

/* Q&A */
export const GET_LIST_INQUIRY = 'GET_LIST_INQUIRY'
export const QA_REQUEST_ERROR = 'QA_REQUEST_ERROR'
