/* Auth */
export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const GET_DEVICE_TOKEN = 'GET_DEVICE_TOKEN'
export const LOGOUT = 'LOGOUT'

/* Tag Managing */
export const CREATE_TAG = 'CREATE_TAG'
export const CREATE_MULTIPLE_TAG = 'CREATE_MULTIPLE_TAG'
export const DELETE_TAG = 'DELETE_TAG'
export const REQUEST_TAG = 'REQUEST_TAG'
export const ERROR_REQUEST_TAG = 'ERROR_REQUEST_TAG'
export const GET_LIST_TAGS = 'GET_LIST_TAGS'
export const ORDER_TAG = 'ORDER_TAG'

/* Notice */
export const REQUEST_NOTICE = 'REQUEST_NOTICE'
export const GET_LIST_NOTICES = 'GET_LIST_NOTICES'
export const ERROR_REQUEST_NOTICE = 'ERROR_REQUEST_NOTICE'
export const NOTICE_DELETE = 'NOTICE_DELETE'
export const EDIT_NOTICE = 'EDIT_NOTICE'
export const ADD_NOTICE = 'ADD_NOTICE'

/* Best Decorating */
export const REQUEST_BESTDECORATING = 'REQUEST_BESTDECORATING'
export const GET_LIST_BESTDECORATING = 'GET_LIST_BESTDECORATING'
export const BEST_DECORATING_ERROR_REQUEST = 'BEST_DECORATING_ERROR_REQUEST'
export const UPDATE_ORDER_BESTDECORATING = 'UPDATE_ORDER_BESTDECORATING'
